#!/bin/bash
SCRIPTPATH="$(cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P)"
CONFIGPATH=$SCRIPTPATH/../../client/public/extension.json

for f in $(ls $SCRIPTPATH/../../common/locales); do
    code="${f%.*}"
    test=$(jq ".languages[] | select(.code == \"$code\")" $CONFIGPATH)
    if [[ $test == "" ]]; then
        echo "$code missing from extension config"
        exit 1;
    fi
done
