#!/bin/bash
SCRIPTPATH="$(cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P)"

for file in $(ls $SCRIPTPATH/../common/locales); do
    diff <(jq 'leaf_paths | join(".")' $SCRIPTPATH/../common/locales/en.json | sort) <(jq 'leaf_paths | join(".")' $SCRIPTPATH/../common/locales/$file | sort)
    if [[ $? -eq 1 ]]; then
        echo "^^^^ $file has mismatching loc keys ^^^^"
        exit 1
    fi
done
