#!/bin/bash

function json_to_csv() {
    jq -r '[paths(scalars) as $path | {"key": $path | join("."), "value": getpath($path)}] | .[] | "\"\(.key)\",\"\",\"\",\"\(.value)\""' $1
}
mkdir -p csv
for locale in $(ls ../extension/src/_locales); do
    echo "Key,Notes,English,Translation" >> csv/$locale.csv
    json_to_csv ../common/locales/$locale.json >> csv/$locale.csv
    json_to_csv ../extension/src/_locales/$locale/messages.json >> csv/$locale.csv
done
