#!/bin/bash
SCRIPTPATH="$(
    cd -- "$(dirname "$0")" >/dev/null 2>&1
    pwd -P
)"
CONFIGPATH=$SCRIPTPATH/../extension/src/pages.json
PAGESCRIPTSPATH=$SCRIPTPATH/../extension/src/entrypoints

for page in $(jq -r ".pages[].script" $CONFIGPATH); do
    if [[ $page = "null" ]]; then
        continue
    fi

    page_basename="${page%.*}"
    page_script_path="$PAGESCRIPTSPATH/$page_basename.ts"

    if [ ! -f "$page_script_path" ]; then
        echo "\"$page_script_path\" referenced by page config is missing"
        exit 1
    fi
done
